### ISSUE TITLE
[FE/FIX] modal video css fix

### ISSUE THREAD

**Issue by JoohwanSeo** [B05-group-project/EatTheMovie#29]
## To-Do
- [x] 모달창 위치 수정
- [x] 상단 케러셀 수정
- [x] index.js -> main.js 이름 변경

###
