### ISSUE TITLE
[FE/REFACTOR]로컬스토리지 관련 로직, 리뷰 작성방식

### ISSUE THREAD

**Issue by YCDM03** [B05-group-project/EatTheMovie#56]
## Description
로컬스토리지 관련로직 전체 리펙토링
날짜에 AM/PM표기 추가
리뷰 작성방식 변경
## To-Do
- [ ] 로컬스토리지 관련 로직 전체 리펙토링
- [ ] 날짜에 AM/PM표기 추가
- [ ] 리뷰 작성방식 변경
