### ISSUE TITLE
[FE/UPDATE] 스켈레톤 UI 구성

### ISSUE THREAD

**Issue by hb9901** [B05-group-project/EatTheMovie#63]
## Description
이미지 로딩 시간동안 보여지는 화면인 스켈레톤 UI 생성

## To-Do
- [ ] 스켈레톤 CSS 추가
- [ ] HTML 스켈레톤 속성 추가
- [ ] js 파일에서 이미지 로딩 시 스켈레톤 속성 삭제

## up-to-date
2024.05.10
